LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := pxa1088-dtbtool.c
LOCAL_CFLAGS += -Wall
LOCAL_MODULE := dtbToolpxa1088
include $(BUILD_HOST_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := pxa1088-dtbtool.c
LOCAL_CFLAGS += -Wall
LOCAL_STATIC_LIBRARIES := libcutils libc
LOCAL_MODULE := utility_dtbToolpxa1088
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_STEM := dtbToolpxa1088
LOCAL_MODULE_CLASS := UTILITY_EXECUTABLES
LOCAL_UNSTRIPPED_PATH := $(PRODUCT_OUT)/symbols
LOCAL_MODULE_PATH := $(PRODUCT_OUT)
LOCAL_FORCE_STATIC_EXECUTABLE := true
include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := pxa1908-dtbtool.c
LOCAL_CFLAGS += -Wall
LOCAL_MODULE := dtbToolpxa1908
include $(BUILD_HOST_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := pxa1908-dtbtool.c
LOCAL_CFLAGS += -Wall
LOCAL_STATIC_LIBRARIES := libcutils libc
LOCAL_MODULE := utility_dtbToolpxa1908
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_STEM := dtbToolpxa1908
LOCAL_MODULE_CLASS := UTILITY_EXECUTABLES
LOCAL_UNSTRIPPED_PATH := $(PRODUCT_OUT)/symbols
LOCAL_MODULE_PATH := $(PRODUCT_OUT)
LOCAL_FORCE_STATIC_EXECUTABLE := true
include $(BUILD_EXECUTABLE)
